# Generated by Django 5.1 on 2024-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
